### ISSUE TITLE
dependsOn doesn't work with CrossProject

### ISSUE THREAD

**Issue by yawnt** [sbt/sbt-eclipse#272]
CrossProject is a scala-js wrapper around Project
If i have something such as this

```
lazy val aproject = CrossProject.in(file("afolder/")).settings(.....)
lazy val aprojectJS = aproject.js
lazy val myproject = Project.in(file("myfolder/"))
                                   .settings(.....) 
                                   .dependsOn(aprojectJS)
```

sbteclipse is gonna generate something like this in the `.classpath`

```
<classpathentry kind="src" path="/aproject" exported="true" combineaccessrules="false"/>
```

instead of the correct

```
<classpathentry kind="src" path="/aprojectJS" exported="true" combineaccessrules="false"/>
```

**Comment by sschaef** [comment]
You are not describing the problem correctly. This does:
```scala
lazy val aproject = crossProject crossType CrossType.Pure in file("afolder/") settings (
  scalaVersion := "2.11.7",
  EclipseKeys.useProjectId := true
)
lazy val aprojectJS = aproject.js
lazy val aprojectJVM = aproject.jvm
lazy val myproject = project.in(file("myfolder/")) settings (
  scalaVersion := "2.11.7"
) dependsOn (aprojectJS)
```
Here, the problem is that the generated project name is `aprojectJS`, but `myproject` has a dependency to `aproject`. If one doesn't use the `useProjectId := true` setting, the project ref is correct but two projects with the name `myproject` are generated.

**Comment by yawnt** [comment]
unfortunately it is mandatory to use the `useProjetId := true` when working with scala.js, otherwise you can't import both in eclipse as they conflict

**Comment by sschaef** [comment]
Why do you want to import both projects? You can't run a project in Eclipse that is compiled to JS, can you?

**Comment by antonkulaga** [comment]
@sschaef because I have to be certain that both jvm and js versions do *compile*. I also want to emphasize there CrossProect.Full is used more often then CrossProject.Pure because it is very common that a developer has to rewrite something to make the lib work for scalajs (so this code goes to js version of the project)

**Comment by yawnt** [comment]
what @antonkulaga said, pretty much ^_^

**Comment by jpercent** [comment]
This seems related to my issue. Maybe someone could take a look and give me a quick tip:
[https://github.com/typesafehub/sbteclipse/issues/319](url)

Most important details pasted for convenience (thanks in advance):

Seems like SBT is using the variable name from build.sbt rather than the file path. A complete example follows. The subproject home/common-play is defined as follows in build.sbt:
`lazy val common_play = project.in(file("common-play"))
.settings(commonSettings: _)
.settings(commonPlaySettings: _)
.enablePlugins(PlayScala)
.settings(libraryDependencies ++= (commonLibs ++ playLibs))
.settings(publish := {})
.settings(publish in Docker := {})
.settings(publishLocal in Docker := {})
.dependsOn(common % "test->test;compile->compile")

`

Note: the value name is common_play, but file path is common-play.

It is subsequently defined as dependency as follows:

lazy val data_manager = project.in(file("data-manager"))
.dependsOn(common_play)
`

In the generated project file the name matches the variable name:
 <projectDescription> <name>common_play</name> <buildSpec> <buildCommand> 

In a dependency .classpath file, under a src refereence the path is listed by the build.sbt variable name:
 <classpathentry kind="src" path="/common_play" exported="true" combineaccessrules="false"/> 
Eclipse tries to find the directory common_play and fails.

**Comment by jpercent** [comment]
I added this to the definition as follows:
 `.settings( name := "common-play" )`

This seemed to fix it. But now the tool is adding a / in front of the library name in the src path entry. Uggh.
